version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "froesef"
    ignore:
      - dependency-name: "io.confluent:kafka-schema-registry"
      - dependency-name: "io.confluent:kafka-rest"
      - dependency-name: "com.amazonaws:*"
      - dependency-name: "org.apache.hadoop:*"
      - dependency-name: "org.apache.kafka:kafka-clients"
      - dependency-name: "io.fabric8:kubernetes-client"
      - dependency-name: "org.jacoco:jacoco-maven-plugin"
      - dependency-name: "org.apache.spark:*"
        versions: ["3.x"]
      - dependency-name: "org.scala-lang:scala-library"
        versions: [ "2.13.x" ]
      - dependency-name: "org.scalatest:*"
        versions: [ "3.3.x" ]
      - dependency-name: "com.squareup.okhttp3:mockwebserver"
        versions: [ "4.x", "5.x" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "froesef"
