version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    default_reviewers:
      - "froesef"
    ignored_updates:
      - match:
          dependency_name: "io.confluent:kafka-schema-registry"
      - match:
          dependency_name: "io.confluent:kafka-rest"
      - match:
          dependency_name: "com.amazonaws:*"
      - match:
          dependency_name: "org.apache.hadoop:*"
      - match:
          dependency_name: "org.apache.kafka:kafka-clients"
      - match:
          dependency_name: "io.fabric8:kubernetes-client"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    default_reviewers:
      - "froesef"
