# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-registry
spec:
  selector:
    matchLabels:
      app: apicurio
  replicas: 1
  template:
    metadata:
      labels:
        app: apicurio
    spec:
      containers:
        - name: apicurio
          image: apicurio/apicurio-registry-mem:1.1.0.Final
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-registry
spec:
  selector:
    app: apicurio
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-registry-np
spec:
  type: NodePort
  selector:
    app: apicurio
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30081
