---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabric-notifier-role
rules:
  - apiGroups:
      - ""
    resources: ["events",]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fabric-runner
  namespace: default
automountServiceAccountToken: true
#imagePullSecrets:
#  - name: {{ .Values.image.imagePullSecret }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fabric-notifier-binding
subjects:
  - kind: ServiceAccount
    namespace: default
    name: fabric-runner
roleRef:
  kind: ClusterRole
  name: fabric-notifier-role
  apiGroup: rbac.authorization.k8s.io
