# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-registry
spec:
  selector:
    matchLabels:
      app: apicurio
  replicas: 1
  template:
    metadata:
      annotations:
#        container.apparmor.security.beta.kubernetes.io/apicurio: runtime/default
      labels:
        app: apicurio
    spec:
      containers:
        - name: apicurio
          image: apicurio/apicurio-registry-mem:1.1.0.Final
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /ccompat/subjects
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
      - name: tmp
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-registry
spec:
  selector:
    app: apicurio
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-registry-np
spec:
  type: NodePort
  selector:
    app: apicurio
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30081
