name: Unit tests

on: push

jobs:
  build-spark-2-4:
    name: Build Spark 2.4.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run test
        run: mvn -B test
      - name: Build Spark base image
        run: docker build -t spark-base:2.4.7 -f src/main/docker/spark/Dockerfile src/main/docker/spark
      - name: Build docker image with jib
        run: mvn -B package jib:dockerBuild -DskipTests -Plocal-to-ghcr
  build-spark-3-0:
    name: Build Spark 3.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run test
        run: mvn -B test -Pspark3
      - name: Build Spark base image
        run: docker build -t spark-base:3.0.1 -f src/main/docker/spark/spark3.Dockerfile src/main/docker/spark
      - name: Build docker image with jib
        run: mvn -B package jib:dockerBuild -DskipTests -Plocal-to-ghcr -Pspark3
